### ISSUE TITLE
Windows: default compiler does not persist

### ISSUE THREAD

**Issue by callumenator** [jacob-carlborg/dvm#31]
Using 0.4.3 in Windows 7, calling ```dvm install 2.066.1``` fetches and installs correctly. Then ```dvm -d use 2.066.1``` adds the compiler directory to my path variable, and it works fine. If I exit the shell, and open a new one, the path settings are gone, and no dmd is found. 

When I installed dvm I did it in a terminal which had admin rights, and I have tried setting the default compiler also with an elevated terminal, but no luck. 

Have I missed something?

**Comment by jacob-carlborg** [comment]
No, it's a bug. I changed the structure a bit in the 0.4.3 release to fix #23. Apparently I made a mistake for when setting the default compiler.

**Comment by jacob-carlborg** [comment]
@Abscissa could you please take a look at this. I thought it would be enough to add the platform path to this [line](https://github.com/jacob-carlborg/dvm/blob/master/dvm/commands/Use.d#L89) but I can't get it to work.

**Comment by Abscissa** [comment]
Hmm, yea, I'll check into that. May not have much time for it until the weekend's over, but I'll see what I can do.

**Comment by jacob-carlborg** [comment]
No rush from my side. It's just that I feel there's some parts regarding the registry I don't know how it works.

**Comment by Abscissa** [comment]
I don't think this issue has anything to do with 0.4.3, I think it may be an issue running dvm on Win7 and up (possibly Vista too, haven't tried). (Or maybe it's a 64-bit Windows thing?)

In any case, on my Win7 64bit machine, I hit the same problem with not only DVM 0.4.3, but also with 0.4.2 and 0.4.0. On my old 32-bit WinXP box, all three DVMs worked fine.

Note, on both machines, I only tested the different DVMs using "dvm-0.4.X... install dvm", I didn't actually wipe DVM or reinstall any DMDs each time. So I'll double-check it that way next, just to be sure. (The XP box started out on 0.4.0, the Win7 box started out on 0.4.3)

**Comment by jacob-carlborg** [comment]
I think that the problem is in 0.4.3 I changed the layout of the installed compilers. The binaries are now placed in `<dvm>/compilers/dmd-<version>/<platform>/bin`. Previously `<platform>` wasn't there. I looked at the `%PATH%` variable and it contained the path without `<platform>`. I think you need to (re)install a compiler to place it in the new path.

**Comment by jacob-carlborg** [comment]
BTW, I do know at least some version of DVM works on Windows 8 (I'm pretty sure it work on 7 as well) because that's how I've installed DMD and it's where I compile DVM. Unless I was still using XP when I compiled the latest version..., hmm.

**Comment by Abscissa** [comment]
> I looked at the %PATH% variable and it contained the path without <platform>. I think you need to (re)install a compiler to place it in the new path.

Ahh, yea, you're right.

**Comment by Abscissa** [comment]
I'm having trouble compiling DVM head on windows. Seems to be an error in mambo?:

```
Z:\MisakaHome\proj\dvm>dvm use 2.066.1

Z:\MisakaHome\proj\dvm>dub build
Building tango 1.0.0+2.066 configuration "static", build type debug.
Running dmd...
tango.io.FileScan is deprecated. Please use tango.io.FilePath.toList or tango.io
.vfs.* instead.
C:\Users\Nick\AppData\Roaming\dub\packages\tango-1.0.0_2.066\tango\io\selector\S
electSelector.d(614): Deprecation: variable tango.io.selector.SelectSelector.Han
dleSet.DefaultSize const field with initializer should be static, __gshared, or
an enum
tango.math.BigInt is deprecated. Please use std.bigint instead.
not yet available for windows
Building mambo 0.0.3 configuration "library", build type debug.
Running dmd...
C:\Users\Nick\AppData\Roaming\dub\packages\mambo-0.0.3\mambo\c\sys\utsname.d(63)
: Error: undefined identifier utsname, did you mean function uname?
FAIL C:\Users\Nick\AppData\Roaming\dub\packages\mambo-0.0.3\.dub\build\library-d
ebug-windows-x86-dmd_2066-31C6838DC3BAB449CAD88A481F3A7503\ mambo staticLibrary
Error executing command build: dmd failed with exit code 1.
```

I tried using build.bat, but then I needed tango, so I attempted to do ```dvm install 2.066.1 -t```, but got:
```
Installing: dmd-2.066.1
Fetching: http://dsource.org/projects/tango/changeset/head/trunk?old_path=%2F&fo
rmat=zip
  [========================================>] 3760/3668 KB

An unknown error occurred:
tango.core.Exception.IOException@.\tango\core\Exception.d(59): C:/Users/Nick/App
Data/Roaming/dvm/tmp/tango/head/trunk/tango.lib: The system cannot find the file
 specified.
----------------
0x0045897E in void tango.io.Path.FS.exception(const(char)[], const(char)[])
0x00458932 in void tango.io.Path.FS.exception(const(char)[])
0x00458CA6 in uint tango.io.Path.FS.getFlags(const(char)[])
0x00458D31 in bool tango.io.Path.FS.isFile(const(char)[])
0x004553CA in void dvm.io.Path.copyMoveImpl(immutable(char)[], immutable(char)[]
, bool) at C:\Users\doob\development\d\dvm\dvm\io\Path.d(85)
0x00455342 in void dvm.io.Path.move(immutable(char)[], immutable(char)[]) at C:\
Users\doob\development\d\dvm\dvm\io\Path.d(71)
0x0040C79C in void dvm.commands.Install.Install.moveTangoFiles() at C:\Users\doo
b\development\d\dvm\dvm\commands\Install.d(276)
0x0040B028 in void dvm.commands.Install.Install.installTango() at C:\Users\doob\
development\d\dvm\dvm\commands\Install.d(200)
0x0040A1AB in void dvm.commands.Install.Install.install(immutable(char)[]) at C:
\Users\doob\development\d\dvm\dvm\commands\Install.d(92)
0x00409EF9 in void dvm.commands.Install.Install.execute() at C:\Users\doob\devel
opment\d\dvm\dvm\commands\Install.d(64)
0x0044010B in void dvm.commands.Command.Command.execute_() at C:\Users\doob\deve
lopment\d\dvm\dvm\commands\Command.d(48)
0x0044009F in void dvm.commands.Command.Command.invoke(immutable(char)[][]...) a
t C:\Users\doob\development\d\dvm\dvm\commands\Command.d(36)
0x00402B88 in void dvm.dvm.Application.Application.handleCommand(immutable(char)
[], immutable(char)[][]) at C:\Users\doob\development\d\dvm\dvm\dvm\Application.
d(138)
0x00402B2A in void dvm.dvm.Application.Application.handleArgs(immutable(char)[][
]) at C:\Users\doob\development\d\dvm\dvm\dvm\Application.d(133)
0x0040306E in D3dvm3dvm11Application11Application12parseOptionsMFZ9__lambda9MFAA
yaZv at C:\Users\doob\development\d\dvm\dvm\dvm\Application.d(208)
0x00439598 in void dvm.util.OptionParser.OptionParser.handleArgs(immutable(char)
[][]) at C:\Users\doob\development\d\dvm\dvm\util\OptionParser.d(112)
0x004394F2 in dvm.util.OptionParser.OptionParser dvm.util.OptionParser.OptionPar
ser.parse(immutable(char)[][], bool) at C:\Users\doob\development\d\dvm\dvm\util
\OptionParser.d(99)
0x00402F14 in void dvm.dvm.Application.Application.parseOptions() at C:\Users\do
ob\development\d\dvm\dvm\dvm\Application.d(212)
0x00402779 in D3dvm3dvm11Application11Application3runMFAAyaZ9__lambda2MFZxi at C
:\Users\doob\development\d\dvm\dvm\dvm\Application.d(64)
0x0040280F in D3dvm3dvm11Application11Application16handleExceptionsMFZ9__lambda1
MFDFZiZi at C:\Users\doob\development\d\dvm\dvm\dvm\Application.d(74)
0x00439A5F in int mambo.util.Use.Use!(int delegate()).Use.opIn(int delegate()) a
t C:\Users\doob\development\d\dvm\mambo\mambo\util\Use.d(80)
0x0040275F in int dvm.dvm.Application.Application.run(immutable(char)[][]) at C:
\Users\doob\development\d\dvm\dvm\dvm\Application.d(62)
0x00402027 in _Dmain at C:\Users\doob\development\d\dvm\dvm\dvm\dvm.d(14)
0x0046F7CE in D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv
0x0046F7A3 in void rt.dmain2._d_run_main(int, char**, extern (C) int function(ch
ar[][])*).runAll()
0x0046F6B9 in _d_run_main
0x00402638 in main
0x004A1881 in mainCRTStartup
0x75F0338A in BaseThreadInitThunk
0x77959F72 in RtlInitializeExceptionChain
0x77959F45 in RtlInitializeExceptionChain
```

**Comment by jacob-carlborg** [comment]
> I'm having trouble compiling DVM head on windows. Seems to be an error in mambo?:

Yeah, I run in to that as well. Apparently I've never compiled Mambo on Windows, I must have used `build.bat` when compiling the latest DVM on Windows.

I'll fix that.

> I tried using build.bat, but then I needed tango, so I attempted to do dvm install 2.066.1 -t, but got

`build.bat` should work if you have Tango installed. `-t` was only ever supposed to be for D1. Now Tango is just like any other third party library. Tango for D1 is somewhat special since it's a new runtime as well.

**Comment by jacob-carlborg** [comment]
I made a fix in master for Mambo. I've not created a new tag yet because I would like to take the opportunity to make sure it works with DMD 2.067.0. first.

**Comment by jacob-carlborg** [comment]
@Abscissa could you please give it a try now, I updated remove "utsname" form the Windows build and updated the code to build with DMD 2.067.0.

**Comment by jacob-carlborg** [comment]
@Abscissa ping, do you have time to work on this?

**Comment by Abscissa** [comment]
Sorry, I'll see if I can try to get back to it this week. (Part of the problem is I haven't being doing as much Windows as I used to. Anything MS just seems to be such a [fire and motion](http://www.joelonsoftware.com/articles/fog0000000339.html) target, especially these days :(. But a good cross-platform DVM is important for D, IMO though.)

**Comment by jacob-carlborg** [comment]
I would really like to do a release of DVM before the next release of DMD and it would be nice if this could be fixed.

**Comment by Abscissa** [comment]
I'm still having trouble compiling this on windows (Win7 64bit). Using the latest DVM master and DMD 2.067.1. Tried two different ways:

1. build.bat: I modified build.bat's rdmd line by replacing ```--exclude=tango ``` with ```-IC:\Users\Nick\AppData\Roaming\dub\packages\tango-1.0.1_2.067\``` and did:

```batch
> dub fetch tango
> build.bat
mambo\mambo\util\Traits.d(154): Deprecation: typedef is removed
mambo\mambo\util\Traits.d(182): Deprecation: typedef is removed
mambo\mambo\core\Array.d(23): Error: undefined identifier 'array'
mambo\mambo\core\Array.d(28): Error: undefined identifier 'join', did you mean 'template min(T...)(T args) if (T.length >= 2)'?
Failed: ["dmd", "-IC:\\Users\\Nick\\AppData\\Roaming\\dub\\packages\\tango-1.0.1_2.067\\", "-Imambo", "-Jresources", "-L+tango", "-Jresources", "-debug", "-g", "-v", "-o-", "dvm\\dvm\\dvm.d", "-Idvm\\dvm"]
```

2. dub: Did this:

```batch
> dub build
Performing "debug" build using dmd for x86.
Building tango 1.0.1+2.067 configuration "static"...
tango.io.FileScan is deprecated. Please use tango.io.FilePath.toList or tango.io.vfs.* instead.
tango.math.BigInt is deprecated. Please use std.bigint instead.
not yet available for windows
C:\Users\Nick\AppData\Roaming\dub\packages\tango-.0.1_2.067\tango\io\selector\SelectSelector.d(156,9): Error: cannot modify struct this._readSet HandleSet with
 immutable members
C:\Users\Nick\AppData\Roaming\dub\packages\tango-.0.1_2.067\tango\io\selector\SelectSelector.d(157,9): Error: cannot modify struct this._writeSet HandleSet wit
h immutable members
C:\Users\Nick\AppData\Roaming\dub\packages\tango-.0.1_2.067\tango\io\selector\SelectSelector.d(158,9): Error: cannot modify struct this._exceptionSet HandleSet
 with immutable members
C:\Users\Nick\AppData\Roaming\dub\packages\tango-.0.1_2.067\tango\io\selector\SelectSelector.d(159,9): Error: cannot modify struct this._selectedReadSet Handle
Set with immutable members
C:\Users\Nick\AppData\Roaming\dub\packages\tango-.0.1_2.067\tango\io\selector\SelectSelector.d(160,9): Error: cannot modify struct this._selectedWriteSet Handl
eSet with immutable members
C:\Users\Nick\AppData\Roaming\dub\packages\tango-.0.1_2.067\tango\io\selector\SelectSelector.d(161,9): Error: cannot modify structthis._selectedExceptionSet HandleSet with immutable members
C:\Users\Nick\AppData\Roaming\dub\packages\tango-1.0.1_2.067\tango\math\IEEE.d(858,13): Deprecation: use std.math.isNaN to deal with NaN operands rather than floating point operator '!<='
C:\Users\Nick\AppData\Roaming\dub\packages\tango-1.0.1_2.067\tango\stdc\math.d(436,55): Deprecation: use std.math.isNaN to deal with NaN operands rather than floating point operator '!>'
C:\Users\Nick\AppData\Roaming\dub\packages\tango-1.0.1_2.067\tango\stdc\math.d(437,55): Deprecation: use std.math.isNaN to deal with NaN operands rather than floating point operator '!>'
C:\Users\Nick\AppData\Roaming\dub\packages\tango-1.0.1_2.067\tango\stdc\math.d(438,55): Deprecation: use std.math.isNaN to deal with NaN operands rather than floating point operator '!>'
C:\Users\Nick\AppData\Roaming\dub\packages\tango-1.0.1_2.067\tango\stdc\math.d(441,55): Deprecation: use std.math.isNaN to deal with NaN operands rather than floating point operator '!>='
C:\Users\Nick\AppData\Roaming\dub\packages\tango-1.0.1_2.067\tango\stdc\math.d(442,55): Deprecation: use std.math.isNaN to deal with NaN operands rather than floating point operator '!>='
C:\Users\Nick\AppData\Roaming\dub\packages\tango-1.0.1_2.067\tango\stdc\math.d(443,55): Deprecation: use std.math.isNaN to deal with NaN operands rather than floating point operator '!>='
C:\Users\Nick\AppData\Roaming\dub\packages\tango-1.0.1_2.067\tango\stdc\math.d(446,55): Deprecation: use std.math.isNaN to deal with NaN operands rather than floating point operator '!<'
C:\Users\Nick\AppData\Roaming\dub\packages\tango-1.0.1_2.067\tango\stdc\math.d(447,55): Deprecation: use std.math.isNaN to deal with NaN operands rather than floating point operator '!<'
C:\Users\Nick\AppData\Roaming\dub\packages\tango-1.0.1_2.067\tango\stdc\math.d(448,55): Deprecation: use std.math.isNaN to deal with NaN operands rather than floating point operator '!<'
C:\Users\Nick\AppData\Roaming\dub\packages\tango-1.0.1_2.067\tango\stdc\math.d(451,55): Deprecation: use std.math.isNaN to deal with NaN operands rather than floating point operator '!<='
C:\Users\Nick\AppData\Roaming\dub\packages\tango-1.0.1_2.067\tango\stdc\math.d(452,55): Deprecation: use std.math.isNaN to deal with NaN operands rather than floating point operator '!<='
C:\Users\Nick\AppData\Roaming\dub\packages\tango-1.0.1_2.067\tango\stdc\math.d(453,55): Deprecation: use std.math.isNaN to deal with NaN operands rather than floating point operator '!<='
C:\Users\Nick\AppData\Roaming\dub\packages\tango-1.0.1_2.067\tango\stdc\math.d(456,55): Deprecation: use std.math.isNaN to deal with NaN operands rather than floating point operator '!<>'
C:\Users\Nick\AppData\Roaming\dub\packages\tango-1.0.1_2.067\tango\stdc\math.d(457,55): Deprecation: use std.math.isNaN to deal with NaN operands rather than floating point operator '!<>'
C:\Users\Nick\AppData\Roaming\dub\packages\tango-1.0.1_2.067\tango\stdc\math.d(458,55): Deprecation: use std.math.isNaN to deal with NaN operands rather than floating point operator '!<>'
dmd failed with exit code 1.
```

**Comment by jacob-carlborg** [comment]
> I'm still having trouble compiling this on windows (Win7 64bit). Using the latest DVM master and DMD 2.067.1. Tried two different ways

Sorry about that. I compiles with Dub and DMD 2.066.1.
